title KAIROS OS (Adaptive Trading Operating System)
linux /vmlinuz-kairos
initrd /initramfs-kairos.img
options root=LABEL=KAIROS_ROOT rootflags=subvol=@ ro quiet loglevel=3 kairos.mode=normal skew_tick=1 nohz=on nohz_full=1-7 rcu_nocbs=1-7 processor.max_cstate=1 apparmor=1 security=apparmor efi=runtime
