title KAIROS OS (Recovery Mode / Emergency Shell)
linux /vmlinuz-kairos
initrd /initramfs-kairos.img
options root=LABEL=KAIROS_ROOT rootflags=subvol=@ ro single emergency systemd.unit=rescue.target kairos.mode=recovery nomodeset
